### ISSUE TITLE
Make a persistent jumplist storage to recover it's state once reopen

### ISSUE THREAD

**Issue by activaigor** [spacian/jumplist#1]
would be great to have jumplist to be saved and restored every time we close and open current project

**Comment by spacian** [comment]
Can you elaborate on why you would like to see this functionality?

I'm using the jumplist very much like a temporary application. When I switch projects I generally don't remember where past jump points were. For persistent navigation I use other extensions like [VSCode Harpoon](https://marketplace.visualstudio.com/items?itemName=tobias-z.vscode-harpoon).

**Comment by activaigor** [comment]
the problem actually only relevant to the cases when i work from the laptop and my RAM is limited which forces me to constantly switching between projects rather then having multiple editor windows opened. in such cases i might run into situations where jumps were made recently and i still remember them but can't use them since they are not there anymore.

thanks for making this extension and for harpoon recommendation, i'll look there!

**Comment by spacian** [comment]
I also develop the extension [vim-marks](https://marketplace.visualstudio.com/items?itemName=spacian.vim-marks) which I want to make persistent over sessions at some point. You could keep an eye on it. I can't promise anything yet, but that might also be a good solution for your problem once it's implemented.

As for the jumplist, I don't think persistency adds a lot for most people, thus I'll close this issue.
